// SPDX-License-Identifier: MIT
//
// NonFungibleToken tests — SECURE PATTERN (witness-derived identity).
//
// ============================================================================
//  PORT NOTES (what changed from the original ownPublicKey-based test)
// ============================================================================
//  The contract no longer uses `ownPublicKey()` for authorization. Identity is
//  derived inside the proof from a private 32-byte secret. Consequently the test
//  model changed:
//
//   * Identity type: `Either<ZswapCoinPublicKey, ContractAddress>` -> the struct
//     `UserPublicKey { bytes: Uint8Array }`. There is no ContractAddress variant
//     and no zero-address-as-Either; the zero/burn account is the all-zero key.
//     The original "Unsafe Transfer" / contract-recipient cases therefore no
//     longer apply and are dropped.
//   * Caller selection: the original `token.as(CALLER)` switched the prover's
//     coin public key. Here a caller is identified by their SECRET, so we switch
//     the witness private state (`{ userSecretKey }`). `derive(secret)` gives the
//     caller's `UserPublicKey`. A wrong secret can no longer impersonate anyone.
//   * Test driver: the repo ships no OpenZeppelin simulator / `#test-utils`, so
//     this suite drives the compiled mock directly via the Compact JS runtime
//     (the same mechanism the production runtime-verification harness uses).
//
//  PREREQUISITES to run:
//   1. Compile the mock full-ZK:
//        compact compile modules/token/test/mocks/MockNonFungibleToken.compact \
//          modules/token/test/artifacts/MockNonFungibleToken
//   2. Install the EXACT runtime the compiled contract pins (see
//      `checkRuntimeVersion(...)` in the generated index.js; 0.16.0 for
//      compactc 0.31.1 / language 0.23.0):
//        npm i -D @midnight-ntwrk/compact-runtime@<pinned>
//   3. npx vitest run modules/token/test/NonFungibleToken.test.ts
// ============================================================================

import { beforeEach, describe, expect, it } from 'vitest';
import {
  createCircuitContext,
  createConstructorContext,
  sampleContractAddress,
} from '@midnight-ntwrk/compact-runtime';
// Generated by compiling MockNonFungibleToken.compact (see PREREQUISITES).
import {
  Contract,
  ledger,
  pureCircuits,
  type NonFungibleToken_UserPublicKey,
} from './artifacts/MockNonFungibleToken/contract/index.js';

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------
const NAME = 'NAME';
const SYMBOL = 'SYMBOL';
const EMPTY_STRING = '';
const INIT = true;
const BAD_INIT = false;

const TOKENID_1 = 1n;
const TOKENID_2 = 2n;
const TOKENID_3 = 3n;
const NON_EXISTENT_TOKEN = 0xdeadn;
const SOME_URI = 'https://openzeppelin.example';
const EMPTY_URI = '';

const ADDR = sampleContractAddress();
const COIN_PK = '0'.repeat(64); // not used for auth; identity comes from secret

const secret = (b: number) => new Uint8Array(32).fill(b);
const SK_OWNER = secret(0x01);
const SK_SPENDER = secret(0x02);
const SK_OTHER = secret(0x03);
const SK_UNAUTH = secret(0x04);
const SK_RECIPIENT = secret(0x05);

const userKey = (sk: Uint8Array): NonFungibleToken_UserPublicKey =>
  pureCircuits.NonFungibleToken_deriveUserPublicKey({ bytes: sk });

const OWNER = userKey(SK_OWNER);
const SPENDER = userKey(SK_SPENDER);
const OTHER = userKey(SK_OTHER);
const UNAUTHORIZED = userKey(SK_UNAUTH);
const RECIPIENT = userKey(SK_RECIPIENT);
const ZERO_KEY: NonFungibleToken_UserPublicKey = { bytes: new Uint8Array(32) };

const keyEq = (
  a: NonFungibleToken_UserPublicKey,
  b: NonFungibleToken_UserPublicKey,
) =>
  Buffer.from(a.bytes).toString('hex') === Buffer.from(b.bytes).toString('hex');

// ---------------------------------------------------------------------------
// Minimal simulator over the Compact JS runtime.
//   * `as(secret)` selects the acting caller by swapping the witness secret.
//   * read-only views return their result; mutating circuits evolve `state`.
// ---------------------------------------------------------------------------
class Sim {
  private contract: Contract<{ userSecretKey: Uint8Array }>;
  private state: any;
  private actor: Uint8Array = SK_OWNER;

  constructor(name: string, symbol: string, init: boolean) {
    this.contract = new Contract<{ userSecretKey: Uint8Array }>(
      this.witnessesFor(SK_OWNER),
    );
    const ps = { userSecretKey: SK_OWNER };
    const res = this.contract.initialState(
      createConstructorContext(ps, COIN_PK),
      name,
      symbol,
      init,
    );
    this.state = res.currentContractState;
  }

  private witnessesFor(sk: Uint8Array) {
    return {
      getUserSecret: (ctx: any): [{ userSecretKey: Uint8Array }, { bytes: Uint8Array }] => [
        ctx.privateState,
        { bytes: sk },
      ],
    };
  }

  /** Select the acting caller by their secret (replaces `token.as(...)`). */
  as(sk: Uint8Array): this {
    this.actor = sk;
    return this;
  }

  private run<R>(name: string, ...args: unknown[]): R {
    this.contract.witnesses = this.witnessesFor(this.actor) as any;
    const ctx = createCircuitContext(ADDR, COIN_PK, this.state, {
      userSecretKey: this.actor,
    });
    const r = (this.contract.circuits as any)[name](ctx, ...args);
    this.state = r.context.currentQueryContext.state;
    // Reset actor to OWNER after each call (mirrors per-call caller selection).
    this.actor = SK_OWNER;
    return r.result as R;
  }

  // Views
  name = () => this.run<string>('name');
  symbol = () => this.run<string>('symbol');
  balanceOf = (a: NonFungibleToken_UserPublicKey) => this.run<bigint>('balanceOf', a);
  ownerOf = (id: bigint) => this.run<NonFungibleToken_UserPublicKey>('ownerOf', id);
  tokenURI = (id: bigint) => this.run<string>('tokenURI', id);
  getApproved = (id: bigint) =>
    this.run<NonFungibleToken_UserPublicKey>('getApproved', id);
  isApprovedForAll = (
    o: NonFungibleToken_UserPublicKey,
    op: NonFungibleToken_UserPublicKey,
  ) => this.run<boolean>('isApprovedForAll', o, op);

  // Witness-derived mutating wrappers
  approve = (to: NonFungibleToken_UserPublicKey, id: bigint) =>
    this.run<[]>('approve', to, id);
  setApprovalForAll = (op: NonFungibleToken_UserPublicKey, ok: boolean) =>
    this.run<[]>('setApprovalForAll', op, ok);
  transferFrom = (
    from: NonFungibleToken_UserPublicKey,
    to: NonFungibleToken_UserPublicKey,
    id: bigint,
  ) => this.run<[]>('transferFrom', from, to, id);

  // Internal circuits (UserPublicKey args, no secret)
  _requireOwned = (id: bigint) =>
    this.run<NonFungibleToken_UserPublicKey>('_requireOwned', id);
  _ownerOf = (id: bigint) =>
    this.run<NonFungibleToken_UserPublicKey>('_ownerOf', id);
  _approve = (
    to: NonFungibleToken_UserPublicKey,
    id: bigint,
    auth: NonFungibleToken_UserPublicKey,
  ) => this.run<[]>('_approve', to, id, auth);
  _checkAuthorized = (
    o: NonFungibleToken_UserPublicKey,
    s: NonFungibleToken_UserPublicKey,
    id: bigint,
  ) => this.run<[]>('_checkAuthorized', o, s, id);
  _isAuthorized = (
    o: NonFungibleToken_UserPublicKey,
    s: NonFungibleToken_UserPublicKey,
    id: bigint,
  ) => this.run<boolean>('_isAuthorized', o, s, id);
  _getApproved = (id: bigint) =>
    this.run<NonFungibleToken_UserPublicKey>('_getApproved', id);
  _setApprovalForAll = (
    o: NonFungibleToken_UserPublicKey,
    op: NonFungibleToken_UserPublicKey,
    ok: boolean,
  ) => this.run<[]>('_setApprovalForAll', o, op, ok);
  _mint = (to: NonFungibleToken_UserPublicKey, id: bigint) =>
    this.run<[]>('_mint', to, id);
  _burn = (id: bigint) => this.run<[]>('_burn', id);
  _transfer = (
    from: NonFungibleToken_UserPublicKey,
    to: NonFungibleToken_UserPublicKey,
    id: bigint,
  ) => this.run<[]>('_transfer', from, to, id);
  _setTokenURI = (id: bigint, uri: string) =>
    this.run<[]>('_setTokenURI', id, uri);

  /** Read the public ledger (e.g. to assert internal mappings). */
  led() {
    return ledger(this.state.data);
  }
}

let token: Sim;

describe('NonFungibleToken (witness-derived identity)', () => {
  describe('initializer and metadata', () => {
    it('should initialize metadata', () => {
      token = new Sim(NAME, SYMBOL, INIT);
      expect(token.name()).toEqual(NAME);
      expect(token.symbol()).toEqual(SYMBOL);
    });

    it('should initialize empty metadata', () => {
      token = new Sim(EMPTY_STRING, EMPTY_STRING, INIT);
      expect(token.name()).toEqual(EMPTY_STRING);
      expect(token.symbol()).toEqual(EMPTY_STRING);
    });

    it('should initialize metadata with special characters', () => {
      token = new Sim('NAME!@#', 'SYMBOL$%^', INIT);
      expect(token.name()).toEqual('NAME!@#');
      expect(token.symbol()).toEqual('SYMBOL$%^');
    });
  });

  beforeEach(() => {
    token = new Sim(NAME, SYMBOL, INIT);
  });

  describe('derivation', () => {
    it('derives distinct, domain-separated keys', () => {
      const admin = pureCircuits.NonFungibleToken_deriveAdminPublicKey({
        bytes: SK_OWNER,
      });
      expect(keyEq(OWNER, SPENDER)).toBe(false);
      // user vs admin derivation must differ for the same secret
      expect(keyEq(OWNER, admin as NonFungibleToken_UserPublicKey)).toBe(false);
    });
  });

  describe('balanceOf', () => {
    it('should return zero when account has no balance', () => {
      expect(token.balanceOf(OWNER)).toEqual(0n);
    });

    it('should return balance after mint', () => {
      token._mint(OWNER, TOKENID_1);
      expect(token.balanceOf(OWNER)).toEqual(1n);
    });

    it('should track balance across multiple mints and burns', () => {
      token._mint(OWNER, TOKENID_1);
      token._mint(OWNER, TOKENID_2);
      token._mint(OWNER, TOKENID_3);
      expect(token.balanceOf(OWNER)).toEqual(3n);
      token._burn(TOKENID_1);
      token._burn(TOKENID_2);
      expect(token.balanceOf(OWNER)).toEqual(1n);
    });

    it('should track balance across transfers', () => {
      token._mint(OWNER, TOKENID_1);
      token._mint(OWNER, TOKENID_2);
      token._transfer(OWNER, RECIPIENT, TOKENID_1);
      expect(token.balanceOf(OWNER)).toEqual(1n);
      expect(token.balanceOf(RECIPIENT)).toEqual(1n);
    });
  });

  describe('ownerOf', () => {
    it('should throw if token does not exist', () => {
      expect(() => token.ownerOf(NON_EXISTENT_TOKEN)).toThrow(
        'NonFungibleToken: Nonexistent Token',
      );
    });

    it('should throw if token has been burned', () => {
      token._mint(OWNER, TOKENID_1);
      token._burn(TOKENID_1);
      expect(() => token.ownerOf(TOKENID_1)).toThrow(
        'NonFungibleToken: Nonexistent Token',
      );
    });

    it('should return owner of an existing token', () => {
      token._mint(OWNER, TOKENID_1);
      expect(keyEq(token.ownerOf(TOKENID_1), OWNER)).toBe(true);
    });
  });

  describe('tokenURI', () => {
    beforeEach(() => {
      token._mint(OWNER, TOKENID_1);
    });

    it('should throw if token does not exist', () => {
      expect(() => token.tokenURI(NON_EXISTENT_TOKEN)).toThrow(
        'NonFungibleToken: Nonexistent Token',
      );
    });

    it('should return empty string for an unset tokenURI', () => {
      expect(token.tokenURI(TOKENID_1)).toEqual(EMPTY_URI);
    });

    it('should return the tokenURI once set', () => {
      token._setTokenURI(TOKENID_1, SOME_URI);
      expect(token.tokenURI(TOKENID_1)).toEqual(SOME_URI);
    });

    it('should maintain tokenURI after transfer', () => {
      token._setTokenURI(TOKENID_1, SOME_URI);
      token._transfer(OWNER, RECIPIENT, TOKENID_1);
      expect(token.tokenURI(TOKENID_1)).toEqual(SOME_URI);
    });
  });

  describe('approve (witness-derived caller)', () => {
    beforeEach(() => {
      token._mint(OWNER, TOKENID_1);
      expect(keyEq(token.getApproved(TOKENID_1), ZERO_KEY)).toBe(true);
    });

    it('should throw if caller is not the owner', () => {
      // SK_UNAUTH derives to UNAUTHORIZED; not the owner -> rejected.
      expect(() => token.as(SK_UNAUTH).approve(SPENDER, TOKENID_1)).toThrow(
        'NonFungibleToken: Invalid Approver',
      );
    });

    it('should approve when caller is the owner', () => {
      token.as(SK_OWNER).approve(SPENDER, TOKENID_1);
      expect(keyEq(token.getApproved(TOKENID_1), SPENDER)).toBe(true);
    });

    it('should allow an operator to approve', () => {
      token.as(SK_OWNER).setApprovalForAll(SPENDER, true);
      token.as(SK_SPENDER).approve(OTHER, TOKENID_1);
      expect(keyEq(token.getApproved(TOKENID_1), OTHER)).toBe(true);
    });

    it('single-token approval does NOT grant approve rights', () => {
      token.as(SK_OWNER).approve(SPENDER, TOKENID_1);
      expect(() => token.as(SK_SPENDER).approve(OTHER, TOKENID_1)).toThrow(
        'NonFungibleToken: Invalid Approver',
      );
    });
  });

  describe('getApproved', () => {
    beforeEach(() => {
      token._mint(OWNER, TOKENID_1);
    });

    it('should throw if token does not exist', () => {
      expect(() => token.getApproved(NON_EXISTENT_TOKEN)).toThrow(
        'NonFungibleToken: Nonexistent Token',
      );
    });

    it('should return zero key if no approval set', () => {
      expect(keyEq(token.getApproved(TOKENID_1), ZERO_KEY)).toBe(true);
    });
  });

  describe('setApprovalForAll / isApprovedForAll', () => {
    it('should reject the zero operator', () => {
      token._mint(OWNER, TOKENID_1);
      expect(() => token.as(SK_OWNER).setApprovalForAll(ZERO_KEY, true)).toThrow(
        'NonFungibleToken: Invalid Operator',
      );
    });

    it('should set and revoke an operator', () => {
      token._mint(OWNER, TOKENID_1);
      token.as(SK_OWNER).setApprovalForAll(SPENDER, true);
      expect(token.isApprovedForAll(OWNER, SPENDER)).toBe(true);
      token.as(SK_OWNER).setApprovalForAll(SPENDER, false);
      expect(token.isApprovedForAll(OWNER, SPENDER)).toBe(false);
    });

    it('operator can transfer owner tokens', () => {
      token._mint(OWNER, TOKENID_1);
      token.as(SK_OWNER).setApprovalForAll(SPENDER, true);
      token.as(SK_SPENDER).transferFrom(OWNER, SPENDER, TOKENID_1);
      expect(keyEq(token.ownerOf(TOKENID_1), SPENDER)).toBe(true);
    });

    it('returns false when no approval set', () => {
      expect(token.isApprovedForAll(OWNER, SPENDER)).toBe(false);
    });
  });

  describe('transferFrom (witness-derived caller — the security boundary)', () => {
    beforeEach(() => {
      token._mint(OWNER, TOKENID_1);
    });

    it('should reject transfer to the zero key', () => {
      expect(() =>
        token.as(SK_OWNER).transferFrom(OWNER, ZERO_KEY, TOKENID_1),
      ).toThrow('NonFungibleToken: Invalid Receiver');
    });

    it('should reject transfer when from is not the owner', () => {
      // caller=OWNER, but claims a wrong `from`. _update auth check passes for
      // OWNER on token #1, but previousOwner != UNAUTHORIZED -> Incorrect Owner.
      expect(() =>
        token.as(SK_OWNER).transferFrom(UNAUTHORIZED, SPENDER, TOKENID_1),
      ).toThrow('NonFungibleToken: Incorrect Owner');
    });

    it('SECURITY: a wrong-secret caller cannot spoof the owner', () => {
      // The old ownPublicKey() attack: pass the victim (OWNER) as `from`.
      // caller derives from SK_UNAUTH, is neither owner nor approved -> rejected.
      expect(() =>
        token.as(SK_UNAUTH).transferFrom(OWNER, UNAUTHORIZED, TOKENID_1),
      ).toThrow('NonFungibleToken: Insufficient Approval');
    });

    it('should reject transfer of an unminted token', () => {
      expect(() =>
        token.as(SK_OWNER).transferFrom(OWNER, SPENDER, NON_EXISTENT_TOKEN),
      ).toThrow('NonFungibleToken: Nonexistent Token');
    });

    it('owner can transfer their own token', () => {
      token.as(SK_OWNER).transferFrom(OWNER, RECIPIENT, TOKENID_1);
      expect(keyEq(token.ownerOf(TOKENID_1), RECIPIENT)).toBe(true);
    });

    it('approved spender can transfer', () => {
      token.as(SK_OWNER).approve(SPENDER, TOKENID_1);
      token.as(SK_SPENDER).transferFrom(OWNER, SPENDER, TOKENID_1);
      expect(keyEq(token.ownerOf(TOKENID_1), SPENDER)).toBe(true);
    });

    it('should reject transfer after approval revocation', () => {
      token.as(SK_OWNER).approve(SPENDER, TOKENID_1);
      token.as(SK_OWNER).approve(ZERO_KEY, TOKENID_1);
      expect(() =>
        token.as(SK_SPENDER).transferFrom(OWNER, SPENDER, TOKENID_1),
      ).toThrow('NonFungibleToken: Insufficient Approval');
    });

    it('should revoke single-token approval after transferFrom', () => {
      token.as(SK_OWNER).approve(SPENDER, TOKENID_1);
      token.as(SK_OWNER).transferFrom(OWNER, OTHER, TOKENID_1);
      expect(keyEq(token.getApproved(TOKENID_1), ZERO_KEY)).toBe(true);
    });
  });

  describe('internal: _approve', () => {
    it('approves if auth is the owner', () => {
      token._mint(OWNER, TOKENID_1);
      token._approve(SPENDER, TOKENID_1, OWNER);
      expect(keyEq(token.getApproved(TOKENID_1), SPENDER)).toBe(true);
    });

    it('throws if auth is unauthorized', () => {
      token._mint(OWNER, TOKENID_1);
      expect(() => token._approve(SPENDER, TOKENID_1, UNAUTHORIZED)).toThrow(
        'NonFungibleToken: Invalid Approver',
      );
    });

    it('approves with zero auth (no auth check)', () => {
      token._mint(OWNER, TOKENID_1);
      token._approve(SPENDER, TOKENID_1, ZERO_KEY);
      expect(keyEq(token.getApproved(TOKENID_1), SPENDER)).toBe(true);
    });
  });

  describe('internal: _isAuthorized / _checkAuthorized', () => {
    beforeEach(() => {
      token._mint(OWNER, TOKENID_1);
    });

    it('owner is authorized', () => {
      expect(token._isAuthorized(OWNER, OWNER, TOKENID_1)).toBe(true);
    });

    it('zero spender is not authorized', () => {
      expect(token._isAuthorized(OWNER, ZERO_KEY, TOKENID_1)).toBe(false);
    });

    it('unauthorized spender is not authorized', () => {
      expect(token._isAuthorized(OWNER, UNAUTHORIZED, TOKENID_1)).toBe(false);
    });

    it('_checkAuthorized throws for unauthorized spender', () => {
      expect(() =>
        token._checkAuthorized(OWNER, UNAUTHORIZED, TOKENID_1),
      ).toThrow('NonFungibleToken: Insufficient Approval');
    });
  });

  describe('internal: _mint', () => {
    it('should reject minting to the zero key', () => {
      expect(() => token._mint(ZERO_KEY, TOKENID_1)).toThrow(
        'NonFungibleToken: Invalid Receiver',
      );
    });

    it('should reject minting an existing token', () => {
      token._mint(OWNER, TOKENID_1);
      expect(() => token._mint(OWNER, TOKENID_1)).toThrow(
        'NonFungibleToken: Invalid Sender',
      );
    });

    it('should mint and assign ownership', () => {
      token._mint(OWNER, TOKENID_1);
      expect(keyEq(token.ownerOf(TOKENID_1), OWNER)).toBe(true);
      expect(token.balanceOf(OWNER)).toEqual(1n);
    });

    it('should mint after burning the same id', () => {
      token._mint(OWNER, TOKENID_1);
      token._burn(TOKENID_1);
      token._mint(OWNER, TOKENID_1);
      expect(keyEq(token.ownerOf(TOKENID_1), OWNER)).toBe(true);
    });
  });

  describe('internal: _burn', () => {
    beforeEach(() => {
      token._mint(OWNER, TOKENID_1);
    });

    it('should burn a token', () => {
      token._burn(TOKENID_1);
      expect(keyEq(token._ownerOf(TOKENID_1), ZERO_KEY)).toBe(true);
      expect(token.balanceOf(OWNER)).toEqual(0n);
    });

    it('should reject burning a nonexistent token', () => {
      expect(() => token._burn(NON_EXISTENT_TOKEN)).toThrow(
        'NonFungibleToken: Invalid Sender',
      );
    });

    it('should clear approval on burn', () => {
      token.as(SK_OWNER).approve(SPENDER, TOKENID_1);
      token._burn(TOKENID_1);
      expect(keyEq(token._getApproved(TOKENID_1), ZERO_KEY)).toBe(true);
    });
  });

  describe('internal: _transfer', () => {
    it('should transfer a token', () => {
      token._mint(OWNER, TOKENID_1);
      token._transfer(OWNER, SPENDER, TOKENID_1);
      expect(keyEq(token.ownerOf(TOKENID_1), SPENDER)).toBe(true);
      expect(token.balanceOf(OWNER)).toEqual(0n);
      expect(token.balanceOf(SPENDER)).toEqual(1n);
    });

    it('should reject transfer to the zero key', () => {
      token._mint(OWNER, TOKENID_1);
      expect(() => token._transfer(OWNER, ZERO_KEY, TOKENID_1)).toThrow(
        'NonFungibleToken: Invalid Receiver',
      );
    });

    it('should reject transfer when from is not the owner', () => {
      token._mint(OWNER, TOKENID_1);
      expect(() => token._transfer(UNAUTHORIZED, SPENDER, TOKENID_1)).toThrow(
        'NonFungibleToken: Incorrect Owner',
      );
    });
  });

  describe('_requireOwned / _ownerOf', () => {
    it('_ownerOf returns zero key for a nonexistent token', () => {
      expect(keyEq(token._ownerOf(NON_EXISTENT_TOKEN), ZERO_KEY)).toBe(true);
    });

    it('_requireOwned throws for a nonexistent token', () => {
      expect(() => token._requireOwned(TOKENID_1)).toThrow(
        'NonFungibleToken: Nonexistent Token',
      );
    });

    it('_requireOwned returns the owner', () => {
      token._mint(OWNER, TOKENID_1);
      expect(keyEq(token._requireOwned(TOKENID_1), OWNER)).toBe(true);
    });
  });
});

// ---------------------------------------------------------------------------
// Uninitialized contract: every circuit must fail the init guard.
// ---------------------------------------------------------------------------
type FailingCall = [method: string, args: unknown[]];

const circuitsToFail: FailingCall[] = [
  ['name', []],
  ['symbol', []],
  ['balanceOf', [OWNER]],
  ['ownerOf', [TOKENID_1]],
  ['tokenURI', [TOKENID_1]],
  ['approve', [OWNER, TOKENID_1]],
  ['getApproved', [TOKENID_1]],
  ['setApprovalForAll', [SPENDER, true]],
  ['isApprovedForAll', [OWNER, SPENDER]],
  ['transferFrom', [OWNER, RECIPIENT, TOKENID_1]],
  ['_requireOwned', [TOKENID_1]],
  ['_ownerOf', [TOKENID_1]],
  ['_approve', [OWNER, TOKENID_1, SPENDER]],
  ['_checkAuthorized', [OWNER, SPENDER, TOKENID_1]],
  ['_isAuthorized', [OWNER, SPENDER, TOKENID_1]],
  ['_getApproved', [TOKENID_1]],
  ['_setApprovalForAll', [OWNER, SPENDER, true]],
  ['_mint', [OWNER, TOKENID_1]],
  ['_burn', [TOKENID_1]],
  ['_transfer', [OWNER, RECIPIENT, TOKENID_1]],
  ['_setTokenURI', [TOKENID_1, EMPTY_URI]],
];

describe('Uninitialized NonFungibleToken', () => {
  let uninit: Sim;
  beforeEach(() => {
    uninit = new Sim(NAME, SYMBOL, BAD_INIT);
  });

  it.each(circuitsToFail)('%s should fail', (method, args) => {
    expect(() => (uninit as any)[method](...args)).toThrow(
      'Initializable: contract not initialized',
    );
  });
});
